# image: ragnar:latest

# services:
  # - docker:dind

# variables:
  # DOCKER_DRIVER: overlay2

# before_script:
  # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - echo_stage
  - lint

echo_job:
  stage: echo_stage
  script:
      - echo "Placeholder"
#     - docker build -t $CI_REGISTRY_IMAGE:latest .
#     - docker push $CI_REGISTRY_IMAGE:latest

lint_backend:
  image: python:latest
  stage: lint
  before_script:
    - pip install --upgrade pip
    - pip install pylint
  script:
    - npm run lint:backend
